spring:
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: Nxd123456 # 密码（默认为空）
    timeout: 6000ms  # 连接超时时长（毫秒）
    jedis:
      pool:
        max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1ms      # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10      # 连接池中的最大空闲连接
        min-idle: 5       # 连接池中的最小空闲连接
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    druid:
      url: jdbc:sqlserver://127.0.0.1:1433;DatabaseName=YHSmartDataRetail
      username: sa
      password: Nxd123456
      initial-size: 20
      max-active: 200
      min-idle: 10
      max-wait: 120000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 40
      time-between-eviction-runs-millis: 120000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        #login-username: admin
        #login-password: admin
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 300
          merge-sql: false
        wall:
          config:
            multi-statement-allow: true
logging:
  level: info
  level.com.nuite: info

smart-data:
  #图片访问项目路径
  picture-url: http://www.yiheiot.com:8002/picture
  #图片上传项目名称
  picture-upload-project: picture
  #NWUser_User表图片文件夹
  nw-user: NWUser
  #NWUser_Assistant表图片文件夹
  assistant: Assistant
  #轮播图文件夹
  sowing_map: sowing